export const GET_LIST_REQUEST = "GET_LIST_REQUEST"
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
export const GET_LIST_FAIL = "GET_LIST_FAIL"

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS"