export const GET_LIST_REQUEST = "GET_LIST_REQUEST"
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
export const GET_LIST_FAIL = "GET_LIST_FAIL"

export const GET_ALL_LIST_REQUEST = "GET_ALL_LIST_REQUEST"
export const GET_ALL_LIST_SUCCESS = "GET_ALL_LIST_SUCCESS"
export const GET_ALL_LIST_FAIL = "GET_ALL_LIST_FAIL"

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL"

export const REMOVE_FROM_LIST_REQUEST = "REMOVE_FROM_LIST_REQUEST"
export const REMOVE_FROM_LIST_SUCCESS = "REMOVE_FROM_LIST_SUCCESS"
export const REMOVE_FROM_LIST_FAIL = "REMOVE_FROM_LIST_FAIL"
export const RESET_STATE_MOVIE = "RESET_STATE_MOVIE"

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST"
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS"
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS"