export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL'


export const RESET_MOVIE = 'RESET_MOVIE'


export const GET_RANDOM_MOVIE_REQUEST = 'GET_RANDOM_MOVIE_REQUEST'
export const GET_RANDOM_MOVIE_SUCCESS = 'GET_RANDOM_MOVIE_SUCCESS'
export const GET_RANDOM_MOVIE_FAIL = 'GET_RANDOM_MOVIE_FAIL'