export  const LOGIN_REQUEST  = "LOGIN_REQUEST"
export  const LOGIN_SUCCESS  = "LOGIN_SUCCESS"
export  const LOGIN_FAIL  = "LOGIN_FAIL"

export  const SIGNUP_REQUEST  = "SIGNUP_REQUEST"
export  const SIGNUP_SUCCESS  = "SIGNUP_SUCCESS"
export  const SIGNUP_FAIL  = "SIGNUP_FAIL"

export  const LOAD_USER_REQUEST  = "LOAD_USER_REQUEST"
export  const LOAD_USER_SUCCESS  = "LOAD_USER_SUCCESS"
export  const LOAD_USER_FAIL  = "LOAD_USER_FAIL"

export  const UPDATE_USER_REQUEST  = "UPDATE_USER_REQUEST"
export  const UPDATE_USER_SUCCESS  = "UPDATE_USER_SUCCESS"
export  const UPDATE_USER_FAIL  = "UPDATE_USER_FAIL"
export  const UPDATE_RESET_USER_FAIL  = "UPDATE_RESET_USER_FAIL"

export  const SIGNOUT_USER_REQUEST  = "SIGNOUT_USER_REQUEST"
export  const SIGNOUT_USER_SUCCESS  = "SIGNOUT_USER_SUCCESS"
export  const SIGNOUT_USER_FAIL  = "SIGNOUT_USER_FAIL"
export  const SIGNOUT_USER_RESET  = "SIGNOUT_USER_RESET"





export  const CLEAR_ERRORS  = "CLEAR_ERRORS"